### ISSUE TITLE
Multiple results in VS2017 test runner

### ISSUE THREAD

**Issue by jannovakcnx** [Microsoft/testfx-docs#37]
When test method attribute is overwritten (exactly the way shown in example RFC3), if first test passes and the other tests are failing, visual studio shows test result as passed.

**Comment by jayaranigarg** [comment]
@jannovakcnx : We acknowledge this to be a bug on our end. We will be addressing this in our upcoming releases.
Kind request - This repo is purely for documentation purposes and please do not post issues here. You can post your queries to [Testfx](https://github.com/Microsoft/testfx/issues)

**Comment by jannovakcnx** [comment]
@jayaranigarg Thank you, should I close the issue here and post it to correct repository?

**Comment by jayaranigarg** [comment]
@jannovakcnx : Yes, that would be great!
