### ISSUE TITLE
Poor Google Search Results

### ISSUE THREAD

**Issue by spottedmahn** [microsoft/testfx-docs#41]
When I search for "ms test assert methods", I'm presented with a list of results on https://msdn.microsoft.com 😪

![image](https://user-images.githubusercontent.com/14079228/39429603-5b730e0c-4c59-11e8-9806-04043095c6c6.png)

---

- Any way SEO can be optimized?
- Any way links to the modern documentation can be added on pages like https://msdn.microsoft.com/en-us/library/microsoft.visualstudio.testtools.unittesting.assert_methods.aspx

**Comment by jayaranigarg** [comment]
Tagging @pvlakshm

**Comment by pvlakshm** [comment]
We have raised this with our internal docs folks ... who are looking into making some improvements. Will keep this updated.

**Comment by spottedmahn** [comment]
Nice, thanks @pvlakshm!

**Comment by Evangelink** [comment]
Closing this issue as nothing was done for a long time. I have some plan to ensure we update/redo public documentation of MSTest and I hope it will drive better SEO.

**Comment by spottedmahn** [comment]
no more MSDN links for me 😊👍

![image](https://user-images.githubusercontent.com/14079228/194871066-b5e054dc-2541-468f-a274-e807f146c923.png)
