### ISSUE TITLE
DataTestMethod vs TestMethod

### ISSUE THREAD

**Issue by jnyrup** [microsoft/testfx-docs#64]
I discovered today that `[DataRow]` can be used with together with `[TestMethod]`, where I had the understanding that `[DataTestMethod]` was required.

Searching both the [source code](https://github.com/Microsoft/testfx/search?l=C%23&q=datatestmethodattribute) and [docs](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.testtools.unittesting.datatestmethodattribute), I'm a bit confused.

I've find no practical difference between the two attributes in the source code, but the documentation for `[DataTestMethod]` says that it is intended for data driven tests.
Then the [examples](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.testtools.unittesting.datarowattribute#examples) for `[DataRow]` uses `[TestMethod]`.

**Comment by jmrnilsson** [comment]
This seems accurate. Some MSTest V1 documentation seems to indicate `[TestMethod]` can be used. But many source on V2 seems to say that `[DataTestMethod]` should be used

- https://www.meziantou.net/mstest-v2-data-tests.htm
- https://stackoverflow.com/questions/2367033/mstest-equivalent-for-nunits-parameterized-tests

**Comment by milbrandt** [comment]
In this [PR of testfx](https://github.com/microsoft/testfx/pull/238) it was reworked and now `DataTestMethodAttribute` inherits from `TestMethodAttribute` and doesn't change anything. Should nowadays be the same in usage.

**Comment by christianarg** [comment]
@milbrandt  Shouldn't someone update the docs:

 https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-with-mstest#add-more-features

and then close this issue

**Comment by Haplois** [comment]
Thanks for pointing this out. I have a PR to fix this issue.
