### ISSUE TITLE
Unable to test decimal values using DataRowAttribute

### ISSUE THREAD

**Issue by RashmiSrinivas1** [microsoft/testfx-docs#79]
Currently we cannot use decimal values in the **DataRow** attribute. 
`[DataRow(1.4m, 2.7m)]`

The solution suggested in Stackoverflow is to pass it as a string and Convert it to decimal. (https://stackoverflow.com/questions/43787007/using-decimal-values-in-datarowattribute) 

Let's say I have an xml attribute of decimal type. Then to test that if I pass it as a string and then convert to decimal it will pass and I'm testing string rather than decimal. So this is not a good solution. Are there any plans to support basic datatypes like decimal in the DataRow attribute?

**Comment by nohwnd** [comment]
The described behavior is limitation of C# not limitation of TestPlatform. To provide types that cannot be provided via attributes, of if you need non static data, you need to use DynamicData attribute: 

```cs
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.Collections.Generic;

namespace UnitTestProject1
{
    [TestClass]
    public class UnitTest1
    {
        // static!
        public static IEnumerable<object[]> TestMethod1Data =>
            // one item per data row
            new[] {
                // one item per parameter, you need to specify the object type
                new object[] { 1m, 2m, 3m },
                new object[] { 13.5m, 178.8m, 192.3m }
            };

        [TestMethod]
        // you can also use a method, but it defaults to property
        [DynamicData(nameof(TestMethod1Data))]
        public void TestMethod1(decimal l, decimal r, decimal expected)
        {
            Assert.AreEqual(expected, l  +  r);
        }
    }
}

```

Here is the source: https://github.com/microsoft/testfx/blob/712986b05ece392cc5b086fa6f0b9018d284bad7/src/TestFramework/MSTest.Core/Attributes/DynamicDataAttribute.cs#L32
