### ISSUE TITLE
Quarterly checkin report?

### ISSUE THREAD

**Issue by AnthonyMastrean** [microsoft/testfx-docs#81]
The [README](https://github.com/microsoft/testfx#roadmap) on the main project says to watch for [quarterly checkins](https://github.com/Microsoft/testfx-docs/tree/master/Quarterly%20Checkins).

![image](https://user-images.githubusercontent.com/217842/74543219-f82e2200-4f12-11ea-9df5-61b5c9b90486.png)

But, there haven't been any since 2019 Q1. Is this still something you plan on doing?

**Comment by nohwnd** [comment]
Hello, I think we will replace it with putting issues into milestones, and release notes on every release. I recently wrote QC for vstest and I like that is shortens the list of fixed issues to the important ones, and that it lists the most active external contributors.

**Comment by Evangelink** [comment]
Agreed with @nohwnd, we are currently doing a release notes at every release so we don't see the need to publish quarterly checkins.
