### ISSUE TITLE
README.md MSTest V2 API documentation may point to wrong or outdated doc

### ISSUE THREAD

**Issue by sebainones** [microsoft/testfx-docs#85]
I might be mistaken but if on the readme file we go the link provided by the  the flollowing line:
_"MSTest V2 API documentation is available here."_

This is the actual link: https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.testtools.unittesting
The page opens with a selected Version of **MSTest.TestFramework 1.32**

Again, I mght be mistaken or confused but I was expecting to see this version : **2.12**
Am I missing something? 
Let me know if I can help with something?

**Comment by Evangelink** [comment]
Hi @sebainones, you are right the documentation on the public doc is not up-to-date. This is something we are planning to work on (see https://github.com/microsoft/testfx/issues/1324).
