### ISSUE TITLE
TestFX documentation is lacking remarks and examples

### ISSUE THREAD

**Issue by SetTrend** [microsoft/testfx-docs#88]
I'm not sure if this is rather a documentation or a product issue, but none of the documentation pages on TestFx I read so far contained a _Remarks_ section, explaining relevant information like motivation, result, effect and example.

**Comment by fgimian** [comment]
I noticed this too and am wondering if I'm missing something?  I also had hoped to see a nicer entrypoint into the documentation with a quick start guide.

Seeing all available attributes isn't very friendly to someone who is not familiar with the framework and where each of these attributes applies.

Perhaps I'm missing something though?

**Comment by Evangelink** [comment]
I am closing this issue as we are merging this repository with the main one (please follow https://github.com/microsoft/testfx/issues/1325 instead).
